# ========== Profile ========== #
# avatar
avatar: /avatar/ikabmi.png
# author name
author: IKABMI
# signature
signature: Ikatan Keluarga Besar MA Manaratul Islam
# SNS (you can custom the order)
social:
  email: ikabmi.manis@gmail.com
  github: //github.com/ikabmi
  # wechat and qq should be a path of qr-code image
  wechat: 
  qq: 
  telegram: 
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: //instagram.com/ikabmi_ 
  stack-overflow: 
  segmentFault: 
  juejin: 
  v2ex: 
  bilibili: 
  linkedin: 
  steam: 
  others: 
  rss: 
# friends
friends:
  enable: false
  friendA:
  friendB:
  friendC: 
about:
  enable: true
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site (good for SEO)
SEO_title: IKABMI
# keywords for site (good for SEO)
SEO_keywords:
  - hexo
  - 'hexo-theme'
  - 'hexo-blog'
# main title shown in header image
main_title: Ikatan Keluarga Besar MA Manaratul Islam
# subtitle
subtitle: Sebuah Perkumpulan yang Mewadahi Lulusan MA Manaratul Islam
# site haeder image
site_header_image: '/intro/manis.jpg'
# post haeder image
post_header_image: '/intro/manis-postbg.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Search ========== #
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We did not find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: 
  valine_appKey: 
  valine_placeHolder: 

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /avatar/ikabmi.png
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.
